/

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -104,26 +104,26 @@ jobs:
           body: "Release with vendor files included."
 
 
-  cleanup:
-    runs-on: ubuntu-latest
-    needs: prepare-release
-    if: always()
+  # cleanup:
+  #   runs-on: ubuntu-latest
+  #   needs: prepare-release
+  #   if: always()
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.GH_TOKEN }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.GH_TOKEN }}
 
-      - name: Git prepare
-        run: |
-          git config --local user.email "durianbohong@gmail.com"
-          git config --local user.name "il4mb"
-          git checkout main
-          git pull origin main
+  #     - name: Git prepare
+  #       run: |
+  #         git config --local user.email "durianbohong@gmail.com"
+  #         git config --local user.name "il4mb"
+  #         git checkout main
+  #         git pull origin main
 
-      - name: Remove vendor directory
-        run: |
-          git rm -r --cached vendor
-          git commit -m "Remove vendor directory" || echo "No changes to commit"
-          git push origin main
+  #     - name: Remove vendor directory
+  #       run: |
+  #         git rm -r --cached vendor
+  #         git commit -m "Remove vendor directory" || echo "No changes to commit"
+  #         git push origin main
